/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSmartTagsRouteImport } from './routes/_authenticated/smart-tags'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedPipelinesRouteRouteImport } from './routes/_authenticated/pipelines/route'
import { Route as AuthenticatedDestinationsRouteRouteImport } from './routes/_authenticated/destinations/route'
import { Route as AuthenticatedSourcesIndexRouteImport } from './routes/_authenticated/sources/index'
import { Route as AuthenticatedPipelinesIndexRouteImport } from './routes/_authenticated/pipelines/index'
import { Route as AuthenticatedDestinationsIndexRouteImport } from './routes/_authenticated/destinations/index'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticatedSettingsWalMonitorRouteImport } from './routes/_authenticated/settings/wal-monitor'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsBatchConfigurationRouteImport } from './routes/_authenticated/settings/batch-configuration'
import { Route as AuthenticatedPipelinesPipelineIdRouteImport } from './routes/_authenticated/pipelines/$pipelineId'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedDestinationsDestinationIdRouteImport } from './routes/_authenticated/destinations/$destinationId'
import { Route as AuthenticatedSourcesSourceIdDetailsRouteImport } from './routes/_authenticated/sources/$sourceId.details'
import { Route as AuthenticatedPipelinesPipelineIdFlowRouteImport } from './routes/_authenticated/pipelines/$pipelineId.flow'

const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSmartTagsRoute = AuthenticatedSmartTagsRouteImport.update({
  id: '/smart-tags',
  path: '/smart-tags',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPipelinesRouteRoute =
  AuthenticatedPipelinesRouteRouteImport.update({
    id: '/pipelines',
    path: '/pipelines',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDestinationsRouteRoute =
  AuthenticatedDestinationsRouteRouteImport.update({
    id: '/destinations',
    path: '/destinations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSourcesIndexRoute =
  AuthenticatedSourcesIndexRouteImport.update({
    id: '/sources/',
    path: '/sources/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPipelinesIndexRoute =
  AuthenticatedPipelinesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPipelinesRouteRoute,
  } as any)
const AuthenticatedDestinationsIndexRoute =
  AuthenticatedDestinationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDestinationsRouteRoute,
  } as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticatedSettingsWalMonitorRoute =
  AuthenticatedSettingsWalMonitorRouteImport.update({
    id: '/wal-monitor',
    path: '/wal-monitor',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsBatchConfigurationRoute =
  AuthenticatedSettingsBatchConfigurationRouteImport.update({
    id: '/batch-configuration',
    path: '/batch-configuration',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedPipelinesPipelineIdRoute =
  AuthenticatedPipelinesPipelineIdRouteImport.update({
    id: '/$pipelineId',
    path: '/$pipelineId',
    getParentRoute: () => AuthenticatedPipelinesRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDestinationsDestinationIdRoute =
  AuthenticatedDestinationsDestinationIdRouteImport.update({
    id: '/$destinationId',
    path: '/$destinationId',
    getParentRoute: () => AuthenticatedDestinationsRouteRoute,
  } as any)
const AuthenticatedSourcesSourceIdDetailsRoute =
  AuthenticatedSourcesSourceIdDetailsRouteImport.update({
    id: '/sources/$sourceId/details',
    path: '/sources/$sourceId/details',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPipelinesPipelineIdFlowRoute =
  AuthenticatedPipelinesPipelineIdFlowRouteImport.update({
    id: '/flow',
    path: '/flow',
    getParentRoute: () => AuthenticatedPipelinesPipelineIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/destinations': typeof AuthenticatedDestinationsRouteRouteWithChildren
  '/pipelines': typeof AuthenticatedPipelinesRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/smart-tags': typeof AuthenticatedSmartTagsRoute
  '/destinations/$destinationId': typeof AuthenticatedDestinationsDestinationIdRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/pipelines/$pipelineId': typeof AuthenticatedPipelinesPipelineIdRouteWithChildren
  '/settings/batch-configuration': typeof AuthenticatedSettingsBatchConfigurationRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/wal-monitor': typeof AuthenticatedSettingsWalMonitorRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/destinations/': typeof AuthenticatedDestinationsIndexRoute
  '/pipelines/': typeof AuthenticatedPipelinesIndexRoute
  '/sources/': typeof AuthenticatedSourcesIndexRoute
  '/pipelines/$pipelineId/flow': typeof AuthenticatedPipelinesPipelineIdFlowRoute
  '/sources/$sourceId/details': typeof AuthenticatedSourcesSourceIdDetailsRoute
}
export interface FileRoutesByTo {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/smart-tags': typeof AuthenticatedSmartTagsRoute
  '/': typeof AuthenticatedIndexRoute
  '/destinations/$destinationId': typeof AuthenticatedDestinationsDestinationIdRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/pipelines/$pipelineId': typeof AuthenticatedPipelinesPipelineIdRouteWithChildren
  '/settings/batch-configuration': typeof AuthenticatedSettingsBatchConfigurationRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/wal-monitor': typeof AuthenticatedSettingsWalMonitorRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/destinations': typeof AuthenticatedDestinationsIndexRoute
  '/pipelines': typeof AuthenticatedPipelinesIndexRoute
  '/sources': typeof AuthenticatedSourcesIndexRoute
  '/pipelines/$pipelineId/flow': typeof AuthenticatedPipelinesPipelineIdFlowRoute
  '/sources/$sourceId/details': typeof AuthenticatedSourcesSourceIdDetailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/_authenticated/destinations': typeof AuthenticatedDestinationsRouteRouteWithChildren
  '/_authenticated/pipelines': typeof AuthenticatedPipelinesRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/smart-tags': typeof AuthenticatedSmartTagsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/destinations/$destinationId': typeof AuthenticatedDestinationsDestinationIdRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/pipelines/$pipelineId': typeof AuthenticatedPipelinesPipelineIdRouteWithChildren
  '/_authenticated/settings/batch-configuration': typeof AuthenticatedSettingsBatchConfigurationRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/wal-monitor': typeof AuthenticatedSettingsWalMonitorRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/_authenticated/destinations/': typeof AuthenticatedDestinationsIndexRoute
  '/_authenticated/pipelines/': typeof AuthenticatedPipelinesIndexRoute
  '/_authenticated/sources/': typeof AuthenticatedSourcesIndexRoute
  '/_authenticated/pipelines/$pipelineId/flow': typeof AuthenticatedPipelinesPipelineIdFlowRoute
  '/_authenticated/sources/$sourceId/details': typeof AuthenticatedSourcesSourceIdDetailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clerk'
    | '/destinations'
    | '/pipelines'
    | '/settings'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/smart-tags'
    | '/destinations/$destinationId'
    | '/errors/$error'
    | '/pipelines/$pipelineId'
    | '/settings/batch-configuration'
    | '/settings/notifications'
    | '/settings/wal-monitor'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/destinations/'
    | '/pipelines/'
    | '/sources/'
    | '/pipelines/$pipelineId/flow'
    | '/sources/$sourceId/details'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/settings'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/smart-tags'
    | '/'
    | '/destinations/$destinationId'
    | '/errors/$error'
    | '/pipelines/$pipelineId'
    | '/settings/batch-configuration'
    | '/settings/notifications'
    | '/settings/wal-monitor'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/destinations'
    | '/pipelines'
    | '/sources'
    | '/pipelines/$pipelineId/flow'
    | '/sources/$sourceId/details'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/_authenticated/destinations'
    | '/_authenticated/pipelines'
    | '/_authenticated/settings'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/smart-tags'
    | '/_authenticated/'
    | '/_authenticated/destinations/$destinationId'
    | '/_authenticated/errors/$error'
    | '/_authenticated/pipelines/$pipelineId'
    | '/_authenticated/settings/batch-configuration'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/wal-monitor'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/_authenticated/destinations/'
    | '/_authenticated/pipelines/'
    | '/_authenticated/sources/'
    | '/_authenticated/pipelines/$pipelineId/flow'
    | '/_authenticated/sources/$sourceId/details'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/smart-tags': {
      id: '/_authenticated/smart-tags'
      path: '/smart-tags'
      fullPath: '/smart-tags'
      preLoaderRoute: typeof AuthenticatedSmartTagsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pipelines': {
      id: '/_authenticated/pipelines'
      path: '/pipelines'
      fullPath: '/pipelines'
      preLoaderRoute: typeof AuthenticatedPipelinesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/destinations': {
      id: '/_authenticated/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof AuthenticatedDestinationsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sources/': {
      id: '/_authenticated/sources/'
      path: '/sources'
      fullPath: '/sources/'
      preLoaderRoute: typeof AuthenticatedSourcesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pipelines/': {
      id: '/_authenticated/pipelines/'
      path: '/'
      fullPath: '/pipelines/'
      preLoaderRoute: typeof AuthenticatedPipelinesIndexRouteImport
      parentRoute: typeof AuthenticatedPipelinesRouteRoute
    }
    '/_authenticated/destinations/': {
      id: '/_authenticated/destinations/'
      path: '/'
      fullPath: '/destinations/'
      preLoaderRoute: typeof AuthenticatedDestinationsIndexRouteImport
      parentRoute: typeof AuthenticatedDestinationsRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/settings/wal-monitor': {
      id: '/_authenticated/settings/wal-monitor'
      path: '/wal-monitor'
      fullPath: '/settings/wal-monitor'
      preLoaderRoute: typeof AuthenticatedSettingsWalMonitorRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/batch-configuration': {
      id: '/_authenticated/settings/batch-configuration'
      path: '/batch-configuration'
      fullPath: '/settings/batch-configuration'
      preLoaderRoute: typeof AuthenticatedSettingsBatchConfigurationRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/pipelines/$pipelineId': {
      id: '/_authenticated/pipelines/$pipelineId'
      path: '/$pipelineId'
      fullPath: '/pipelines/$pipelineId'
      preLoaderRoute: typeof AuthenticatedPipelinesPipelineIdRouteImport
      parentRoute: typeof AuthenticatedPipelinesRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/destinations/$destinationId': {
      id: '/_authenticated/destinations/$destinationId'
      path: '/$destinationId'
      fullPath: '/destinations/$destinationId'
      preLoaderRoute: typeof AuthenticatedDestinationsDestinationIdRouteImport
      parentRoute: typeof AuthenticatedDestinationsRouteRoute
    }
    '/_authenticated/sources/$sourceId/details': {
      id: '/_authenticated/sources/$sourceId/details'
      path: '/sources/$sourceId/details'
      fullPath: '/sources/$sourceId/details'
      preLoaderRoute: typeof AuthenticatedSourcesSourceIdDetailsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pipelines/$pipelineId/flow': {
      id: '/_authenticated/pipelines/$pipelineId/flow'
      path: '/flow'
      fullPath: '/pipelines/$pipelineId/flow'
      preLoaderRoute: typeof AuthenticatedPipelinesPipelineIdFlowRouteImport
      parentRoute: typeof AuthenticatedPipelinesPipelineIdRoute
    }
  }
}

interface AuthenticatedDestinationsRouteRouteChildren {
  AuthenticatedDestinationsDestinationIdRoute: typeof AuthenticatedDestinationsDestinationIdRoute
  AuthenticatedDestinationsIndexRoute: typeof AuthenticatedDestinationsIndexRoute
}

const AuthenticatedDestinationsRouteRouteChildren: AuthenticatedDestinationsRouteRouteChildren =
  {
    AuthenticatedDestinationsDestinationIdRoute:
      AuthenticatedDestinationsDestinationIdRoute,
    AuthenticatedDestinationsIndexRoute: AuthenticatedDestinationsIndexRoute,
  }

const AuthenticatedDestinationsRouteRouteWithChildren =
  AuthenticatedDestinationsRouteRoute._addFileChildren(
    AuthenticatedDestinationsRouteRouteChildren,
  )

interface AuthenticatedPipelinesPipelineIdRouteChildren {
  AuthenticatedPipelinesPipelineIdFlowRoute: typeof AuthenticatedPipelinesPipelineIdFlowRoute
}

const AuthenticatedPipelinesPipelineIdRouteChildren: AuthenticatedPipelinesPipelineIdRouteChildren =
  {
    AuthenticatedPipelinesPipelineIdFlowRoute:
      AuthenticatedPipelinesPipelineIdFlowRoute,
  }

const AuthenticatedPipelinesPipelineIdRouteWithChildren =
  AuthenticatedPipelinesPipelineIdRoute._addFileChildren(
    AuthenticatedPipelinesPipelineIdRouteChildren,
  )

interface AuthenticatedPipelinesRouteRouteChildren {
  AuthenticatedPipelinesPipelineIdRoute: typeof AuthenticatedPipelinesPipelineIdRouteWithChildren
  AuthenticatedPipelinesIndexRoute: typeof AuthenticatedPipelinesIndexRoute
}

const AuthenticatedPipelinesRouteRouteChildren: AuthenticatedPipelinesRouteRouteChildren =
  {
    AuthenticatedPipelinesPipelineIdRoute:
      AuthenticatedPipelinesPipelineIdRouteWithChildren,
    AuthenticatedPipelinesIndexRoute: AuthenticatedPipelinesIndexRoute,
  }

const AuthenticatedPipelinesRouteRouteWithChildren =
  AuthenticatedPipelinesRouteRoute._addFileChildren(
    AuthenticatedPipelinesRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsBatchConfigurationRoute: typeof AuthenticatedSettingsBatchConfigurationRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsWalMonitorRoute: typeof AuthenticatedSettingsWalMonitorRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsBatchConfigurationRoute:
      AuthenticatedSettingsBatchConfigurationRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsWalMonitorRoute: AuthenticatedSettingsWalMonitorRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDestinationsRouteRoute: typeof AuthenticatedDestinationsRouteRouteWithChildren
  AuthenticatedPipelinesRouteRoute: typeof AuthenticatedPipelinesRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedSmartTagsRoute: typeof AuthenticatedSmartTagsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedSourcesIndexRoute: typeof AuthenticatedSourcesIndexRoute
  AuthenticatedSourcesSourceIdDetailsRoute: typeof AuthenticatedSourcesSourceIdDetailsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDestinationsRouteRoute:
    AuthenticatedDestinationsRouteRouteWithChildren,
  AuthenticatedPipelinesRouteRoute:
    AuthenticatedPipelinesRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedSmartTagsRoute: AuthenticatedSmartTagsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedSourcesIndexRoute: AuthenticatedSourcesIndexRoute,
  AuthenticatedSourcesSourceIdDetailsRoute:
    AuthenticatedSourcesSourceIdDetailsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
